name: "Go setup"

description: "Job to setup go and install the dependencies for the project"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Install build dependencies
      run: sudo apt install build-essential gcc -y
      shell: bash

    - name: Install go dependencies
      run: go get -t ./...
      shell: bash