name: "Build release versions"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches:
      - main
      - beta

jobs:
  build-macos-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build macos amd64
        run: GOARCH=amd64 GOOS=darwin go build -tags main -o bin/sam_darwin_amd64 .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*

  build-macos-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build macos arm64
        run: GOARCH=arm64 GOOS=darwin go build -tags main -o bin/sam_darwin_arm64 .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build linux amd64
        run: GOARCH=amd64 GOOS=linux go build -tags main -o bin/sam_linux_amd64 .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build linux arm64
        run: GOARCH=arm64 GOOS=linux go build -tags main -o bin/sam_linux_arm64 .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*

  build-windows-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build windows amd64
        run: GOARCH=amd64 GOOS=windows go build -tags main -o bin/sam_windows_amd64.exe .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*

  build-windows-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/workflows/common/go-setup
      - name: Build windows arm64
        run: GOARCH=arm64 GOOS=windows go build -tags main -o bin/sam_windows_arm64.exe .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sam-builds-${{ env.GITHUB_SHA }}
          path: bin/*