name: "Build release versions"

on:
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches:
      - main
      - beta

jobs:
  build-macos-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build macos amd64
        run: GOARCH=amd64 GOOS=darwin go build -tags main -o bin/sam_darwin_amd64 .

  build-macos-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build macos arm64
        run: GOARCH=arm64 GOOS=darwin go build -tags main -o bin/sam_darwin_arm64 .

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build linux amd64
        run: GOARCH=amd64 GOOS=linux go build -tags main -o bin/sam_linux_amd64 .

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build linux arm64
        run: GOARCH=arm64 GOOS=linux go build -tags main -o bin/sam_linux_arm64 .

  build-windows-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build windows amd64
        run: GOARCH=amd64 GOOS=windows go build -tags main -o bin/sam_windows_amd64.exe .

  build-windows-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/common/go-setup.yml
      - name: Build windows arm64
        run: GOARCH=arm64 GOOS=windows go build -tags main -o bin/sam_windows_arm64.exe .

  upload-build-artifacts:
    needs:
      - build-macos-amd64
      - build-macos-arm64
      - build-linux-amd64
      - build-linux-arm64
      - build-windows-amd64
      - build-windows-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: bin/*