name: Lint
on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.go'
      - '.github/workflows/lint.yaml'
      - '.github/workflows/common/go-setup/action.yaml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/lint.yaml'
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/common/go-setup

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest