name: Lint
on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.go'
      - '.github/workflows/lint.yaml'
  pull_request: {}
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/common/go-setup

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.20.4
          args: -v --print-issued-lines