name: Lint
on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.go'
      - '.github/workflows/lint.yaml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/lint.yaml'
jobs:
  linting:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/common/go-setup

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -v --print-issued-lines