name: "Test and Build"
on:
  workflow_dispatch: {}
  push:
    paths:
      - '**.go'
      - '.github/workflows/test-and-build.yaml'
      - '.github/workflows/common/go-setup/action.yaml'
jobs:
  test-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/common/go-setup

      - name: Install dev dependencies
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev -y

      - name: Run tests
        run: make test

      - name: Build application
        run: make build