name: "Test and Build"
on: [push]
jobs:
  test-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/workflows/common/go-setup

      - name: Run tests
        run: make test

      - name: Build application
        run: make build